#!name=美团去广告
#!desc=美团去广告
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/weiboad.png
#!author=simon

hostname = flowplus.meituan.net, s3plus.meituan.net

# 美团 去广告
^https:\/\/flowplus\.meituan\.net\/v1\/mss_\w+\/linglong\/\d+\.jpg$ url reject-dict
^https:\/\/s3plus\.meituan\.net\/v1\/mss_\w+\/(brandcpt-vedio|waimai-alita)\/\w+\.zip$ url reject-dict